name: main

on: pull_request

env:
  CI: true

jobs:
  main:
    timeout-minutes: 15
    name: 'main'
    runs-on: ubuntu-latest
    steps:
      - name: 'hello world'
        run: | 
          echo "hello world"
          date
