name: main

on:
  pull_request:
    types:
      - labeled
      - opened
      - edited
      - synchronize
      - reopened

env:
  CI: true

jobs:
  main:
    timeout-minutes: 15
    name: 'main'
    runs-on: ubuntu-latest
    steps:
      - name: 'hello world'
        run: 'echo hello world'
