name: on_release

on:
  pull_request_target:
    types:
      - opened
    branches:
      - 'main'

env:
  CI: true

jobs:
  on_release:
    timeout-minutes: 15
    name: 'main'
    runs-on: ubuntu-latest
    steps:
      - name: 'test test'
        run: |
          echo "test test"
