name: Release

on:
  push:
    branches:
      - main

# concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js 18.16.1
        uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'

      - name: 'Install dependencies'
        run: npm ci

      - name: Create Release Pull Request
        id: changesets_action
        uses: changesets/action@v1
        with:
          # Creates/updates release PR if pending changesets
          # version: pnpm libraries:version
          commit: '/libraries/* release'
          title: '`/libraries/*` release'     
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug Release
        env:
          output1: ${{needs.release.changesets_action.pullRequestNumber}}"
          output2: ${{needs.changesets_action.pullRequestNumber}}"
          # output3: ${{changesets_action.pullRequestNumber}}"   
        run: |
          echo "pull request number: ${output1}"
          echo "pull request number: ${output2}"
